spring.application.name=cars

# Configure DataSource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.pwd=pass
spring.sql.init.platform=h2

# Hibernate settings
spring.jpa.hibernate.ddl-auto=none

# Optional: Show SQL statements in the console
spring.jpa.show-sql=true

server.port=5005

# Configure H2 Console
# (Optional, but useful for development; accessible at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration